/**
 * DashboardNarrativePanel - AI-generated insights panel for dashboards
 *
 * Displays executive summary and widget-level insights generated by AI
 */

import React, { useState, useEffect } from 'react';
import {
  Drawer,
  Box,
  Typography,
  IconButton,
  Divider,
  CircularProgress,
  Alert,
  Chip,
  Card,
  CardContent,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  Collapse,
  Button,
  Tooltip,
  Skeleton
} from '@mui/material';
import {
  Close as CloseIcon,
  AutoAwesome as InsightsIcon,
  TrendingUp as TrendingUpIcon,
  TrendingDown as TrendingDownIcon,
  TrendingFlat as TrendingFlatIcon,
  Warning as WarningIcon,
  CheckCircle as CheckIcon,
  Lightbulb as RecommendationIcon,
  ExpandMore as ExpandMoreIcon,
  ExpandLess as ExpandLessIcon,
  Refresh as RefreshIcon,
  AccessTime as TimeIcon
} from '@mui/icons-material';
import api from '../../services/api';

const DashboardNarrativePanel = ({
  open,
  onClose,
  dashboardId,
  dashboardName
}) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [narrative, setNarrative] = useState(null);
  const [expandedWidgets, setExpandedWidgets] = useState({});

  useEffect(() => {
    if (open && dashboardId) {
      fetchNarrative();
    }
  }, [open, dashboardId]);

  const fetchNarrative = async () => {
    setLoading(true);
    setError(null);

    try {
      // Try to get cached narrative first for faster initial load
      try {
        const cachedResponse = await api.get(`/api/v1/dashboards/${dashboardId}/narrative/cached`);
        if (cachedResponse.data?.narrative) {
          setNarrative(cachedResponse.data.narrative);
        }
      } catch {
        // No cached version, that's fine
      }

      // Generate fresh narrative
      const response = await api.post(`/api/v1/dashboards/${dashboardId}/narrative`, {
        include_widget_insights: true,
        max_widgets: 10
      });

      setNarrative(response.data);
    } catch (err) {
      console.error('Failed to fetch narrative:', err);
      setError(err.response?.data?.detail || 'Failed to generate insights');
    } finally {
      setLoading(false);
    }
  };

  const toggleWidgetExpand = (index) => {
    setExpandedWidgets(prev => ({
      ...prev,
      [index]: !prev[index]
    }));
  };

  const getTrendIcon = (trend) => {
    switch (trend?.toLowerCase()) {
      case 'up':
      case 'increasing':
        return <TrendingUpIcon color="success" />;
      case 'down':
      case 'decreasing':
        return <TrendingDownIcon color="error" />;
      default:
        return <TrendingFlatIcon color="action" />;
    }
  };

  const getSeverityColor = (severity) => {
    switch (severity?.toLowerCase()) {
      case 'critical':
        return 'error';
      case 'warning':
        return 'warning';
      default:
        return 'info';
    }
  };

  const renderExecutiveSummary = () => {
    const summary = narrative?.executive_summary;
    if (!summary) return null;

    return (
      <Box sx={{ mb: 3 }}>
        <Typography variant="h6" gutterBottom sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <InsightsIcon color="primary" />
          Executive Summary
        </Typography>

        <Typography variant="body1" sx={{ mb: 2, fontStyle: 'italic' }}>
          {summary.summary}
        </Typography>

        {/* Key Metrics */}
        {summary.key_metrics?.length > 0 && (
          <Box sx={{ mb: 2 }}>
            <Typography variant="subtitle2" color="text.secondary" gutterBottom>
              Key Metrics
            </Typography>
            <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
              {summary.key_metrics.map((metric, idx) => (
                <Card key={idx} variant="outlined" sx={{ minWidth: 150 }}>
                  <CardContent sx={{ py: 1, px: 2, '&:last-child': { pb: 1 } }}>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                      {getTrendIcon(metric.trend)}
                      <Typography variant="caption" color="text.secondary">
                        {metric.metric}
                      </Typography>
                    </Box>
                    <Typography variant="h6" sx={{ fontWeight: 'bold' }}>
                      {metric.value}
                    </Typography>
                    {metric.insight && (
                      <Typography variant="caption" color="text.secondary">
                        {metric.insight}
                      </Typography>
                    )}
                  </CardContent>
                </Card>
              ))}
            </Box>
          </Box>
        )}

        {/* Highlights */}
        {summary.highlights?.length > 0 && (
          <Box sx={{ mb: 2 }}>
            <Typography variant="subtitle2" color="text.secondary" gutterBottom>
              Highlights
            </Typography>
            <List dense disablePadding>
              {summary.highlights.map((highlight, idx) => (
                <ListItem key={idx} disablePadding sx={{ py: 0.5 }}>
                  <ListItemIcon sx={{ minWidth: 32 }}>
                    <CheckIcon color="success" fontSize="small" />
                  </ListItemIcon>
                  <ListItemText primary={highlight} />
                </ListItem>
              ))}
            </List>
          </Box>
        )}

        {/* Concerns */}
        {summary.concerns?.length > 0 && (
          <Box sx={{ mb: 2 }}>
            <Typography variant="subtitle2" color="text.secondary" gutterBottom>
              Areas of Concern
            </Typography>
            <List dense disablePadding>
              {summary.concerns.map((concern, idx) => (
                <ListItem key={idx} disablePadding sx={{ py: 0.5 }}>
                  <ListItemIcon sx={{ minWidth: 32 }}>
                    <WarningIcon color="warning" fontSize="small" />
                  </ListItemIcon>
                  <ListItemText primary={concern} />
                </ListItem>
              ))}
            </List>
          </Box>
        )}

        {/* Recommendations */}
        {summary.recommendations?.length > 0 && (
          <Box>
            <Typography variant="subtitle2" color="text.secondary" gutterBottom>
              Recommendations
            </Typography>
            <List dense disablePadding>
              {summary.recommendations.map((rec, idx) => (
                <ListItem key={idx} disablePadding sx={{ py: 0.5 }}>
                  <ListItemIcon sx={{ minWidth: 32 }}>
                    <RecommendationIcon color="primary" fontSize="small" />
                  </ListItemIcon>
                  <ListItemText primary={rec} />
                </ListItem>
              ))}
            </List>
          </Box>
        )}
      </Box>
    );
  };

  const renderWidgetInsights = () => {
    const insights = narrative?.widget_insights;
    if (!insights?.length) return null;

    return (
      <Box>
        <Typography variant="h6" gutterBottom sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          Widget Insights
          <Chip label={insights.length} size="small" />
        </Typography>

        <List disablePadding>
          {insights.map((insight, idx) => (
            <Card key={idx} variant="outlined" sx={{ mb: 1 }}>
              <CardContent sx={{ py: 1.5, px: 2, '&:last-child': { pb: 1.5 } }}>
                <Box
                  sx={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    cursor: 'pointer'
                  }}
                  onClick={() => toggleWidgetExpand(idx)}
                >
                  <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                    {getTrendIcon(insight.trend)}
                    <Typography variant="subtitle2">
                      {insight.widget_title}
                    </Typography>
                    <Chip
                      label={insight.confidence || 'medium'}
                      size="small"
                      variant="outlined"
                      color={
                        insight.confidence === 'high' ? 'success' :
                        insight.confidence === 'low' ? 'warning' : 'default'
                      }
                      sx={{ height: 20, fontSize: '0.7rem' }}
                    />
                  </Box>
                  <IconButton size="small">
                    {expandedWidgets[idx] ? <ExpandLessIcon /> : <ExpandMoreIcon />}
                  </IconButton>
                </Box>

                <Collapse in={expandedWidgets[idx]}>
                  <Box sx={{ mt: 1.5, pl: 4 }}>
                    <Typography variant="body2" color="text.secondary">
                      {insight.insight}
                    </Typography>
                    {insight.comparison && (
                      <Typography variant="caption" color="text.secondary" sx={{ mt: 0.5, display: 'block' }}>
                        {insight.comparison}
                      </Typography>
                    )}
                  </Box>
                </Collapse>
              </CardContent>
            </Card>
          ))}
        </List>
      </Box>
    );
  };

  const renderLoadingSkeleton = () => (
    <Box>
      <Skeleton variant="text" width="60%" height={32} sx={{ mb: 2 }} />
      <Skeleton variant="rectangular" height={80} sx={{ mb: 2, borderRadius: 1 }} />
      <Skeleton variant="text" width="40%" height={24} sx={{ mb: 1 }} />
      <Skeleton variant="rectangular" height={60} sx={{ mb: 1, borderRadius: 1 }} />
      <Skeleton variant="rectangular" height={60} sx={{ mb: 1, borderRadius: 1 }} />
      <Skeleton variant="rectangular" height={60} sx={{ borderRadius: 1 }} />
    </Box>
  );

  return (
    <Drawer
      anchor="right"
      open={open}
      onClose={onClose}
      PaperProps={{
        sx: { width: { xs: '100%', sm: 400, md: 450 } }
      }}
    >
      <Box sx={{ p: 2 }}>
        {/* Header */}
        <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 2 }}>
          <Box>
            <Typography variant="h6" sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
              <InsightsIcon color="primary" />
              AI Insights
            </Typography>
            <Typography variant="caption" color="text.secondary">
              {dashboardName}
            </Typography>
          </Box>
          <Box>
            <Tooltip title="Refresh insights">
              <IconButton onClick={fetchNarrative} disabled={loading} size="small">
                <RefreshIcon />
              </IconButton>
            </Tooltip>
            <IconButton onClick={onClose} size="small">
              <CloseIcon />
            </IconButton>
          </Box>
        </Box>

        <Divider sx={{ mb: 2 }} />

        {/* Content */}
        {loading && !narrative ? (
          renderLoadingSkeleton()
        ) : error ? (
          <Alert
            severity="error"
            action={
              <Button color="inherit" size="small" onClick={fetchNarrative}>
                Retry
              </Button>
            }
          >
            {error}
          </Alert>
        ) : narrative ? (
          <>
            {/* Generation timestamp */}
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5, mb: 2 }}>
              <TimeIcon fontSize="small" color="action" />
              <Typography variant="caption" color="text.secondary">
                Generated {new Date(narrative.generated_at).toLocaleString()}
              </Typography>
              {loading && <CircularProgress size={14} sx={{ ml: 1 }} />}
            </Box>

            {renderExecutiveSummary()}

            <Divider sx={{ my: 2 }} />

            {renderWidgetInsights()}
          </>
        ) : (
          <Box sx={{ textAlign: 'center', py: 4 }}>
            <InsightsIcon sx={{ fontSize: 48, color: 'action.disabled', mb: 2 }} />
            <Typography color="text.secondary">
              Click the button to generate AI insights for this dashboard
            </Typography>
            <Button
              variant="contained"
              startIcon={<InsightsIcon />}
              onClick={fetchNarrative}
              sx={{ mt: 2 }}
            >
              Generate Insights
            </Button>
          </Box>
        )}
      </Box>
    </Drawer>
  );
};

export default DashboardNarrativePanel;
